{% if (PROMPT_CONTEXT or PROMPT_STDIN) %}
CONTEXT:
{{PROMPT_CONTEXT or ""}} 
{{PROMPT_STDIN or ""}}
{% endif %}
{% if PROMPT_ROLE %}
ROLE:
{{PROMPT_ROLE}}
{% endif %}
INSTRUCTIONS:
{{PROMPT_INSTRUCTIONS or ""}}
{{PROMPT_INPUT or ""}}
{% if PROMPT_OUTPUT %}
OUPUT:
{{PROMPT_OUTPUT}}
{% endif %}
{% if PROMPT_OUTPUT %}
EXAMPLE:
{{PROMPT_EXAMPLE}}
{% endif %}