#!/bin/bash
# Demo script for ADR-0011 Context Injection feature

echo "=== Context Injection Demo ==="
echo ""
echo "This demonstrates how context commands execute and inject"
echo "their output into the LLM prompt automatically."
echo ""

echo "Example 1: Using --exec flag for ad-hoc context"
echo "Command: cllm --exec 'uname -a' 'What OS am I using?'"
echo ""
echo "This would execute 'uname -a' and inject its output like:"
echo "--- Context: CLI Command 1 ---"
uname -a
echo "--- End Context ---"
echo ""
echo "What OS am I using?"
echo ""

echo "=========================================="
echo ""

echo "Example 2: Using Cllmfile configuration"
echo "File: debug.Cllmfile.yml"
echo ""
echo "context_commands:"
echo "  - name: 'Git Status'"
echo "    command: 'git status --short'"
echo ""
echo "Command: cllm --config debug 'Analyze my changes'"
echo ""
echo "This would automatically execute and inject:"
echo "--- Context: Git Status ---"
git status --short 2>/dev/null || echo "(not in git repo)"
echo "--- End Context ---"
echo ""
echo "Analyze my changes"
echo ""

echo "=========================================="
echo ""
echo "Key Features:"
echo "  ✓ Commands run in parallel by default"
echo "  ✓ Timeout protection (default: 10s)"
echo "  ✓ Configurable failure handling (warn/ignore/fail)"
echo "  ✓ Supports both CLI flags and Cllmfile configs"
echo "  ✓ CLI --exec commands append to config commands"
echo ""
echo "See ADR-0011 and examples/configs/ for more details!"
