# Code Review Configuration
# Usage: git diff | cllm --config code-review

# Use GPT-4 for code analysis
model: "gpt-4"

# Moderate temperature for balanced analysis
temperature: 0.5

# Allow comprehensive reviews
max_tokens: 1500

# System message for code review guidance
default_system_message: |
  You are an expert code reviewer. Analyze the provided code and provide:

  1. **Issues & Bugs**: Identify potential bugs, edge cases, or errors
  2. **Best Practices**: Suggest improvements following language conventions
  3. **Performance**: Note any performance concerns or optimizations
  4. **Security**: Flag security vulnerabilities or risks
  5. **Readability**: Recommend clarity improvements
  6. **Testing**: Suggest test cases or validation needs

  Be constructive, specific, and actionable in your feedback.

# Reliability
timeout: 90
num_retries: 2

# Fallback models
fallbacks:
  - "claude-3-opus-20240229"
  - "gpt-3.5-turbo-16k"
