# Entity Extraction Configuration
# Extracts named entities from text with structured output
#
# Usage: cat document.txt | cllm --config extraction

model: "gpt-4o"
temperature: 0 # Use deterministic output for structured data
max_tokens: 2000

# Reference external JSON schema file
json_schema_file: "examples/schemas/entity-extraction.json"

# Optional: Set a default system message
default_system_message: "You are a precise entity extraction system. Extract all named entities from the provided text."

# Optional: Add fallback models
fallbacks:
  - "gpt-4o-mini"
  - "gpt-3.5-turbo"
